#
# Module manifest for module 'DisplaySettings'
#
# Generated by: Sapphire Becker
#
# Generated on: 3/19/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DisplaySettings.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = '73b34956-d1b5-43e9-9b95-47481c7bf04c'

# Author of this module
Author = 'Sapphire Becker'

# Company or vendor of this module
CompanyName = 'LogicPlace'

# Copyright statement for this module
Copyright = '(c) Sapphire Becker. MIT licensed.'

# Description of the functionality provided by this module
Description = 'cmdlet to query and change display settings'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @("Get-ScreenDevices", "Set-ScreenSettings")

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("DisplaySettings", "Resolution")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/logicplace/DisplaySettings/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/logicplace/DisplaySettings'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/logicplace/DisplaySettings/blob/main/README.md'

}

